language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run build
before_deploy:
  - rm -rf node_modules src test
deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  skip_cleanup: true
  app: coinmech
notifications:
  email: false
