export const PLAYER_EDIT_REQUESTED = 'PLAYER_EDIT_REQUESTED';
export const PLAYER_DELETE_REQUESTED = 'PLAYER_DELETE_REQUESTED';
export const PLAYER_DELETE_CLOSED = 'PLAYER_DELETE_CLOSED';
export const PLAYER_PROPERTY_UPDATED = 'PLAYER_PROPERTY_UPDATED';
export const PLAYER_CREATED = 'PLAYER_CREATED';
export const PLAYER_UPDATED = 'PLAYER_UPDATED';
export const BALANCE_UPDATED = 'BALANCE_UPDATED';
export const UPDATING_BALANCE = 'UPDATING_BALANCE';

export const PLAYER_DELETED = 'PLAYER_DELETED';
export const BALANCE_UPDATE_CLOSED = 'BALANCE_UPDATE_CLOSED';
export const BALANCE_UPDATE_REQUESTED = 'BALANCE_UPDATE_REQUESTED';
export const REQUEST_PLAYERS = 'REQUEST_PLAYERS';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';
export const PLAYER_ADD_REQUESTED = 'PLAYER_ADD_REQUESTED';
export const PLAYER_EDIT_CLOSED = 'PLAYER_EDIT_CLOSED';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';

export const RECEIVE_MACHINES = 'RECEIVE_MACHINES';
export const REQUEST_MACHINES = 'REQUEST_MACHINES';
export const MACHINE_EDIT_CLOSED = 'MACHINE_EDIT_CLOSED';
export const MACHINE_ADD_REQUESTED = 'MACHINE_ADD_REQUESTED';
export const MACHINE_PROPERTY_UPDATED = 'MACHINE_PROPERTY_UPDATED';
export const MACHINE_EDIT_REQUESTED = 'MACHINE_EDIT_REQUESTED';
export const MACHINE_DELETE_REQUESTED = 'MACHINE_DELETE_REQUESTED';
export const MACHINE_DELETE_CLOSED = 'MACHINE_DELETE_CLOSED';
export const MACHINE_CREATED = 'MACHINE_CREATED';
export const MACHINE_DELETED = 'MACHINE_DELETED';
export const MACHINE_UPDATED = 'MACHINE_UPDATED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const AUTH_INITIALIZED = 'AUTH_INITIALIZED';

export const RECEIVE_CARDS = 'RECEIVE_CARDS';
export const REQUEST_CARDS = 'REQUEST_CARDS';

export const CARD_EDIT_REQUESTED = 'CARD_EDIT_REQUESTED';
export const CARD_EDIT_CLOSED = 'CARD_EDIT_CLOSED';
export const CARD_PROPERTY_UPDATED = 'CARD_PROPERTY_UPDATED';
export const CARD_ASSIGNED = 'CARD_ASSIGNED';

export const DEVICE_STATUS_UPDATED = 'DEVICE_STATUS_UPDATED';
